version: '3.8'
services:
  nextjs-app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "if [ -f yarn.lock ]; then yarn dev; else npm run dev; fi"
